export type PrimarySelection =
  | 'dashboard'
  | 'createContainer'
  | 'updateContainer'
  | 'addDataType'
  | 'updateDataType'
  | 'addDataItem'
  | 'browseContainers'
  | 'browseTypes'
  | 'publishDataItemVerification'
  | 'attachChild'
  | 'addOwner'
  | 'removeOwner'
  | 'items'
  | 'receivedItems'
  | 'itemVerifications'
  | 'receivedItemVerifications';
